
data_path : ""
run_testing : False
run_training : False
seed : 42
train :
  lr : 5e-4
  chunk_size : 16384
  max_steps : 1000
  batch_size : 1
  num_rays : 1024
  color_bkgd : "white"
  batch_over_images : True
test :
  n_poses : 20
  gen_poses : False
  
model :
  n_enc : 10
  near_thresh : 2.
  far_thresh : 6.
logs :
  save_every : 1
  show_every : 10
  save_checkpoint_every : 500
  save_rendered_img_every : 1
saving: 
  save_mask : False
  rendered_images_folder : "Results"
  model_name : "Classic_Nerf_"
  masked_folder : ""
  drive_path : ""
  save_ckp_path : ""
  load_ckp_path : Null
  gen_vid : False
 

 